name: Telegram Toyota Bot

permissions:
  contents: write  # необходимо для коммита файлов обратно в репо

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run bot
        working-directory: ${{ github.workspace }}
        run: python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit updated sent_links and log
        if: always()
        working-directory: ${{ github.workspace }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin "${{ github.ref_name }}" || true
          git add sent_links.txt bot.log
          git diff --staged --quiet || git commit -m "Update bot state [skip ci]"
          git push origin "${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bot-artifacts
          path: |
            ${{ github.workspace }}/bot.log
            ${{ github.workspace }}/sent_links.txt
