name: Telegram Toyota Bot

on:
  schedule:
    - cron: "0 */7 * * *"  # каждые 7 часов
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run bot
        working-directory: ${{ github.workspace }}
        run: python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Upload log and sent_links
        uses: actions/upload-artifact@v4
        with:
          name: bot-artifacts
          path: |
            ${{ github.workspace }}/bot.log
            ${{ github.workspace }}/sent_links.txt
